config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#home"
  resources :users, only: [:index, :show]

  resources :posts do
    resources :comments
  end

  resources :comments, only: [:edit, :update, :destroy] do
    resources :comments
  end

  resources :events do
    resources :comments
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :events, dependent: :destroy  
  has_many :comments, dependent: :destroy
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/views/users/index.html.erb
<h1 align="center"> All users: </h1>
  <% @users.each do |user| %>
  <div class="row center">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="username">
          <%= link_to user.name, user_path(user) %>
        </div>
        <% if user.posts.any? %>
          <p>Posts: <%= user.posts.count %></p>
        <% else %>
          <p>Posts: 0 </p>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>

app/views/users/show.html.erb
<h2 align="center">Name: <%= @user.name %><h2>
  <div align="center">
    <% if (user_signed_in? && @user == current_user)  %>
      <%= link_to "New post", new_post_path,
                               class: "btn btn-md btn-success" %>
    <% end %>
  </div>
  <div class="container col-xs-8">
    <div>
      <% @posts.each do |post| %>
        <div class="row center">
          <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
              <div class="title">
                <h3><%= post.title %></h3>
              </div>
              <div class="description">
                <p><%= post.description %></p>
              </div>
              <div class="post-actions">
                <% if (user_signed_in? && @user == current_user)  %>
                  <%= link_to "Edit post", edit_post_path(post),
                                           class: "btn btn-xs btn-success" %>
                  <%= link_to "Delete post", post_path(post),
                                             method: :delete,
                                             data: {confirm: "Are you sure?"},
                                             class: "btn btn-xs btn-danger" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="comment_form">
            <%= render partial: 'comments/form', locals: {
              resource: post, comment: Comment.new
              } %>
          </div>
          <h3>Comments</h3>
          <%= render post.comments %>
        </div>
      <% end %>
    </div>
</div>