config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#home"
  resources :users, only: [:index, :show]

  resources :posts do
    resources :comments
  end

  resources :comments, only: [:edit, :update, :destroy] do
    resources :comments
  end

  resources :events do
    resources :comments
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  start_time  :datetime
#  end_time    :datetime
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_events_on_user_id  (user_id)
#

class Event < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :update, :destroy, :edit]

  def index
    @events = Event.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.create(event_params)
    if @event
      flash[:success] = "Event was successfuly saved"
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:success] = "Event was successfuly updated"
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "Event was successfuly deleted"
    redirect_to events_path
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:description, :title, :user_id, :start_time,
                                   :end_time)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@event, html: {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :title%>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :title, class: "form-control",
                         placeholder: "title of events", autofocus: true%>
      </div>
   </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :description%>
      </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows:8, class: "form-control",
                           placeholder: "Small description for event"%>
        </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :start_time%>
      </div>
        <div class="col-sm-8">
          <%= f.datetime_select :start_time%>
        </div>
    </div>
    <div class="form-group">
      <div class='control-label col-sm-2'>
        <%= f.label :end_time%>
      </div>
        <div class="col-sm-8">
          <%= f.datetime_select :end_time%>
        </div>
    </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit  class:"btn btn-primary btn-lg"%>
    </div>
  </div>
    <% end %>
   <div class="col-xs-5 col-xs-offset-5">
     <%= link_to "Back to events", events_path, class:"btn btn-success btn-md"%>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<h1 align="center"> Edit event </h1>
<%= render 'form' %>

app/views/events/index.html.erb
<h1 align="center"> All events: </h1>
<div align="center">
  <% if user_signed_in? %>
    <%= link_to "New event", new_event_path, class: "btn btn-md btn-success" %>
  <% end %><hr>
</div>
  <% @events.each do |event| %>
    <div class="row center">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="titleforpost">
            <%= link_to event.title.capitalize, event_path(event) %>
          </div>
          <div class="description">
            <i><%= truncate(event.description.capitalize , length: 100) %></i>
          </div>
          <div class="author">
            Author: <%= event.user.name %>
          </div>
          <div class="start_time">
            Start: <%= event.start_time %>
          </div>
          <div class="end_time">
            End: <%= event.end_time %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/events/new.html.erb
<h1 align="center"> New event </h1>
<%= render 'form' %>

app/views/events/show.html.erb
<div class="row center">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="title">
        <h3><%= @event.title %></h3>
      </div>
      <div class="description">
        <p><%= @event.description %></p>
      </div>
      <div class="start_time">
        <p>Start date: <%= @event.start_time %></p>
      </div>
      <div class="end_time">
        <p>Finish date: <%= @event.end_time %></p>
      </div>
      <div class="event-actions">
        <% if (user_signed_in? && @event.user == current_user)  %>
          <%= link_to "Edit event", edit_event_path(@event),
                                   class: "btn btn-xs btn-success" %>
          <%= link_to "Delete event", event_path(@event),
                                     method: :delete,
                                     data: {confirm: "Are you sure?"},
                                     class: "btn btn-xs btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="comment_form">
    <%= render partial: 'comments/form', locals: {
      resource: @event, comment: Comment.new
      } %>
  </div>
  <h3>Comments</h3>
  <%= render @event.comments %>
</div>